# Generated by Django 6.0.5 on 2026-05-27 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_title", models.CharField(max_length=200)),
                (
                    "room_image",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=200)),
                (
                    "guest_photo",
                    models.ImageField(blank=True, null=True, upload_to="guest_photos/"),
                ),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.listing",
                    ),
                ),
            ],
        ),
    ]
